/* FILE: lmt_httpd.def

This file was automatically created by the program lmt_make.pl

DO NOT EDIT THIS FILE!!!

Rather edit the file lmt_httpd.def that is the source 

*/
#include <stdio.h>
#include "basext.h"

extern SLFST CGI_SLFST[];
extern SLFST MT_SLFST[];
MODLIST StaticallyLinkedModules[] ={
  {"cgi" , (void *)CGI_SLFST },
  {"mt" , (void *)MT_SLFST },
  { NULL, NULL },
  };
