/* FILE: lmt_none.def

This file was automatically created by the program lmt_make.pl

DO NOT EDIT THIS FILE!!!

Rather edit the file lmt_none.def that is the source 

*/
#include <stdio.h>
#include "basext.h"

MODLIST StaticallyLinkedModules[] ={
  { NULL, NULL },
  };
