/* FILE: lmt_cio.def

This file was automatically created by the program lmt_make.pl

DO NOT EDIT THIS FILE!!!

Rather edit the file lmt_cio.def that is the source 

*/
#include <stdio.h>
#include "basext.h"

extern SLFST CIO_SLFST[];
MODLIST StaticallyLinkedModules[] ={
  {"cio" , (void *)CIO_SLFST },
  { NULL, NULL },
  };
