/* FILE: lmt_wx.def

This file was automatically created by the program lmt_make.pl

DO NOT EDIT THIS FILE!!!

Rather edit the file lmt_wx.def that is the source 

*/
#include <stdio.h>
#include "basext.h"

extern SLFST WX_SLFST[];
MODLIST StaticallyLinkedModules[] ={
  {"wx" , (void *)WX_SLFST },
  { NULL, NULL },
  };
