call mkth devguide
call mkth ug
call mkth auxfiles
call mkth source
call mkth eszterengine
call mkth docudoc
call mkthm mod_bdb
call mkthm mod_cgi
call mkthm mod_cio
call mkthm mod_curl
call mkthm mod_dbg
call mkthm mod_gd
call mkthm mod_hash
call mkthm mod_mt
call mkthm mod_mysql
call mkthm mod_nt
call mkthm mod_odbc
call mkthm mod_re
call mkthm mod_t
call mkthm mod_trial
call mkthm mod_zlib
call mksamples samplebas
call mksamples regtest
