/*
--GNU LGPL
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/
#include <stdio.h>
#include "../command.h"


COMMAND(EXTOPF)
  ERROR(COMMAND_ERROR_NOTIMP); /* ? */
END

COMMAND(EXTOPK)
  ERROR(COMMAND_ERROR_NOTIMP); /* ! */
END

/* As a default behaviour this operator returns the same number
   as it gets, because some lasy BASIC programmers write

   OPEN "file" for input as #1

   and they have HARD TIME finding it!
*/
COMMAND(EXTOPL)
  NODE nItem;
  VARIABLE Op1;

  /* this is an operator and not a command, therefore we do not have our own mortal list */
  USE_CALLER_MORTALS;

  /* evaluate the parameters */
  nItem = PARAMETERLIST;
  Op1 = EVALUATEEXPRESSION(CAR(nItem));
  RESULT = Op1;
END

COMMAND(EXTOPO)
  ERROR(COMMAND_ERROR_NOTIMP); /* ` */
END
COMMAND(EXTOPP)
  ERROR(COMMAND_ERROR_NOTIMP); /* ' */
END
COMMAND(EXTOPQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* @ */
END

COMMAND(EXTOPAC)
  ERROR(COMMAND_ERROR_NOTIMP); /* +^ */
END

COMMAND(EXTOPAD)
  ERROR(COMMAND_ERROR_NOTIMP); /* +< */
END

COMMAND(EXTOPAE)
  ERROR(COMMAND_ERROR_NOTIMP); /* +> */
END

COMMAND(EXTOPAF)
  ERROR(COMMAND_ERROR_NOTIMP); /* +? */
END

COMMAND(EXTOPAG)
  ERROR(COMMAND_ERROR_NOTIMP); /* += */
END

COMMAND(EXTOPAH)
  ERROR(COMMAND_ERROR_NOTIMP); /* +* */
END

COMMAND(EXTOPAI)
  ERROR(COMMAND_ERROR_NOTIMP); /* +/ */
END

COMMAND(EXTOPAJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* +% */
END

COMMAND(EXTOPAK)
  ERROR(COMMAND_ERROR_NOTIMP); /* +! */
END

COMMAND(EXTOPAL)
  ERROR(COMMAND_ERROR_NOTIMP); /* +# */
END

COMMAND(EXTOPAM)
  ERROR(COMMAND_ERROR_NOTIMP); /* +& */
END

COMMAND(EXTOPAN)
  ERROR(COMMAND_ERROR_NOTIMP); /* +\ */
END

COMMAND(EXTOPAO)
  ERROR(COMMAND_ERROR_NOTIMP); /* +` */
END

COMMAND(EXTOPAP)
  ERROR(COMMAND_ERROR_NOTIMP); /* +' */
END

COMMAND(EXTOPAQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* +@ */
END

COMMAND(EXTOPBC)
  ERROR(COMMAND_ERROR_NOTIMP); /* -^ */
END

COMMAND(EXTOPBD)
  ERROR(COMMAND_ERROR_NOTIMP); /* -< */
END

COMMAND(EXTOPBE)
  ERROR(COMMAND_ERROR_NOTIMP); /* -> */
END

COMMAND(EXTOPBF)
  ERROR(COMMAND_ERROR_NOTIMP); /* -? */
END

COMMAND(EXTOPBG)
  ERROR(COMMAND_ERROR_NOTIMP); /* -= */
END

COMMAND(EXTOPBH)
  ERROR(COMMAND_ERROR_NOTIMP); /* -* */
END

COMMAND(EXTOPBI)
  ERROR(COMMAND_ERROR_NOTIMP); /* -/ */
END

COMMAND(EXTOPBJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* -% */
END

COMMAND(EXTOPBK)
  ERROR(COMMAND_ERROR_NOTIMP); /* -! */
END

COMMAND(EXTOPBL)
  ERROR(COMMAND_ERROR_NOTIMP); /* -# */
END

COMMAND(EXTOPBM)
  ERROR(COMMAND_ERROR_NOTIMP); /* -& */
END

COMMAND(EXTOPBN)
  ERROR(COMMAND_ERROR_NOTIMP); /* -\ */
END

COMMAND(EXTOPBO)
  ERROR(COMMAND_ERROR_NOTIMP); /* -` */
END

COMMAND(EXTOPBP)
  ERROR(COMMAND_ERROR_NOTIMP); /* -' */
END

COMMAND(EXTOPBQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* -@ */
END

COMMAND(EXTOPCC)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^^ */
END

COMMAND(EXTOPCD)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^< */
END

COMMAND(EXTOPCE)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^> */
END

COMMAND(EXTOPCF)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^? */
END

COMMAND(EXTOPCG)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^= */
END

COMMAND(EXTOPCH)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^* */
END

COMMAND(EXTOPCI)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^/ */
END

COMMAND(EXTOPCJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^% */
END

COMMAND(EXTOPCK)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^! */
END

COMMAND(EXTOPCL)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^# */
END

COMMAND(EXTOPCM)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^& */
END

COMMAND(EXTOPCN)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^\ */
END

COMMAND(EXTOPCO)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^` */
END

COMMAND(EXTOPCP)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^' */
END

COMMAND(EXTOPCQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* ^@ */
END

COMMAND(EXTOPDC)
  ERROR(COMMAND_ERROR_NOTIMP); /* <^ */
END

COMMAND(EXTOPDD)
  ERROR(COMMAND_ERROR_NOTIMP); /* << */
END

COMMAND(EXTOPDF)
  ERROR(COMMAND_ERROR_NOTIMP); /* <? */
END

COMMAND(EXTOPDH)
  ERROR(COMMAND_ERROR_NOTIMP); /* <* */
END

COMMAND(EXTOPDI)
  ERROR(COMMAND_ERROR_NOTIMP); /* </ */
END

COMMAND(EXTOPDJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* <% */
END

COMMAND(EXTOPDK)
  ERROR(COMMAND_ERROR_NOTIMP); /* <! */
END

COMMAND(EXTOPDL)
  ERROR(COMMAND_ERROR_NOTIMP); /* <# */
END

COMMAND(EXTOPDM)
  ERROR(COMMAND_ERROR_NOTIMP); /* <& */
END

COMMAND(EXTOPDN)
  ERROR(COMMAND_ERROR_NOTIMP); /* <\ */
END

COMMAND(EXTOPDO)
  ERROR(COMMAND_ERROR_NOTIMP); /* <` */
END

COMMAND(EXTOPDP)
  ERROR(COMMAND_ERROR_NOTIMP); /* <' */
END

COMMAND(EXTOPDQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* <@ */
END

COMMAND(EXTOPEC)
  ERROR(COMMAND_ERROR_NOTIMP); /* >^ */
END

COMMAND(EXTOPED)
  ERROR(COMMAND_ERROR_NOTIMP); /* >< */
END

COMMAND(EXTOPEE)
  ERROR(COMMAND_ERROR_NOTIMP); /* >> */
END

COMMAND(EXTOPEF)
  ERROR(COMMAND_ERROR_NOTIMP); /* >? */
END

COMMAND(EXTOPEH)
  ERROR(COMMAND_ERROR_NOTIMP); /* >* */
END

COMMAND(EXTOPEI)
  ERROR(COMMAND_ERROR_NOTIMP); /* >/ */
END

COMMAND(EXTOPEJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* >% */
END

COMMAND(EXTOPEK)
  ERROR(COMMAND_ERROR_NOTIMP); /* >! */
END

COMMAND(EXTOPEL)
  ERROR(COMMAND_ERROR_NOTIMP); /* ># */
END

COMMAND(EXTOPEM)
  ERROR(COMMAND_ERROR_NOTIMP); /* >& */
END

COMMAND(EXTOPEN)
  ERROR(COMMAND_ERROR_NOTIMP); /* >\ */
END

COMMAND(EXTOPEO)
  ERROR(COMMAND_ERROR_NOTIMP); /* >` */
END

COMMAND(EXTOPEP)
  ERROR(COMMAND_ERROR_NOTIMP); /* >' */
END

COMMAND(EXTOPEQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* >@ */
END

COMMAND(EXTOPFC)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?^ */
END

COMMAND(EXTOPFD)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?< */
END

COMMAND(EXTOPFE)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?> */
END

COMMAND(EXTOPFF)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?? */
END

COMMAND(EXTOPFG)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?= */
END

COMMAND(EXTOPFH)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?* */
END

COMMAND(EXTOPFI)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?/ */
END

COMMAND(EXTOPFJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?% */
END

COMMAND(EXTOPFK)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?! */
END

COMMAND(EXTOPFL)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?# */
END

COMMAND(EXTOPFM)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?& */
END

COMMAND(EXTOPFN)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?\ */
END

COMMAND(EXTOPFO)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?` */
END

COMMAND(EXTOPFP)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?' */
END

COMMAND(EXTOPFQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* ?@ */
END

COMMAND(EXTOPGC)
  ERROR(COMMAND_ERROR_NOTIMP); /* =^ */
END

COMMAND(EXTOPGD)
  ERROR(COMMAND_ERROR_NOTIMP); /* =< */
END

COMMAND(EXTOPGE)
  ERROR(COMMAND_ERROR_NOTIMP); /* => */
END

COMMAND(EXTOPGF)
  ERROR(COMMAND_ERROR_NOTIMP); /* =? */
END

COMMAND(EXTOPGG)
  ERROR(COMMAND_ERROR_NOTIMP); /* == */
END

COMMAND(EXTOPGH)
  ERROR(COMMAND_ERROR_NOTIMP); /* =* */
END

COMMAND(EXTOPGI)
  ERROR(COMMAND_ERROR_NOTIMP); /* =/ */
END

COMMAND(EXTOPGJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* =% */
END

COMMAND(EXTOPGK)
  ERROR(COMMAND_ERROR_NOTIMP); /* =! */
END

COMMAND(EXTOPGL)
  ERROR(COMMAND_ERROR_NOTIMP); /* =# */
END

COMMAND(EXTOPGM)
  ERROR(COMMAND_ERROR_NOTIMP); /* =& */
END

COMMAND(EXTOPGN)
  ERROR(COMMAND_ERROR_NOTIMP); /* =\ */
END

COMMAND(EXTOPGO)
  ERROR(COMMAND_ERROR_NOTIMP); /* =` */
END

COMMAND(EXTOPGP)
  ERROR(COMMAND_ERROR_NOTIMP); /* =' */
END

COMMAND(EXTOPGQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* =@ */
END

COMMAND(EXTOPHC)
  ERROR(COMMAND_ERROR_NOTIMP); /* *^ */
END

COMMAND(EXTOPHD)
  ERROR(COMMAND_ERROR_NOTIMP); /* *< */
END

COMMAND(EXTOPHE)
  ERROR(COMMAND_ERROR_NOTIMP); /* *> */
END

COMMAND(EXTOPHF)
  ERROR(COMMAND_ERROR_NOTIMP); /* *? */
END

COMMAND(EXTOPHG)
  ERROR(COMMAND_ERROR_NOTIMP); /* *= */
END

COMMAND(EXTOPHH)
  ERROR(COMMAND_ERROR_NOTIMP); /* ** */
END

COMMAND(EXTOPHI)
  ERROR(COMMAND_ERROR_NOTIMP); /* */ 
END

COMMAND(EXTOPHJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* *% */
END

COMMAND(EXTOPHK)
  ERROR(COMMAND_ERROR_NOTIMP); /* *! */
END

COMMAND(EXTOPHL)
  ERROR(COMMAND_ERROR_NOTIMP); /* *# */
END

COMMAND(EXTOPHM)
  ERROR(COMMAND_ERROR_NOTIMP); /* *& */
END

COMMAND(EXTOPHN)
  ERROR(COMMAND_ERROR_NOTIMP); /* *\ */
END

COMMAND(EXTOPHO)
  ERROR(COMMAND_ERROR_NOTIMP); /* *` */
END

COMMAND(EXTOPHP)
  ERROR(COMMAND_ERROR_NOTIMP); /* *' */
END

COMMAND(EXTOPHQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* *@ */
END

COMMAND(EXTOPIC)
  ERROR(COMMAND_ERROR_NOTIMP); /* /^ */
END

COMMAND(EXTOPID)
  ERROR(COMMAND_ERROR_NOTIMP); /* /< */
END

COMMAND(EXTOPIE)
  ERROR(COMMAND_ERROR_NOTIMP); /* /> */
END

COMMAND(EXTOPIF)
  ERROR(COMMAND_ERROR_NOTIMP); /* /? */
END

COMMAND(EXTOPIG)
  ERROR(COMMAND_ERROR_NOTIMP); /* /= */
END

COMMAND(EXTOPIH)
  ERROR(COMMAND_ERROR_NOTIMP); /* /* */
END

COMMAND(EXTOPII)
  ERROR(COMMAND_ERROR_NOTIMP); /* // */
END

COMMAND(EXTOPIJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* /% */
END

COMMAND(EXTOPIK)
  ERROR(COMMAND_ERROR_NOTIMP); /* /! */
END

COMMAND(EXTOPIL)
  ERROR(COMMAND_ERROR_NOTIMP); /* /# */
END

COMMAND(EXTOPIM)
  ERROR(COMMAND_ERROR_NOTIMP); /* /& */
END

COMMAND(EXTOPIN)
  ERROR(COMMAND_ERROR_NOTIMP); /* /\ */
END

COMMAND(EXTOPIO)
  ERROR(COMMAND_ERROR_NOTIMP); /* /` */
END

COMMAND(EXTOPIP)
  ERROR(COMMAND_ERROR_NOTIMP); /* /' */
END

COMMAND(EXTOPIQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* /@ */
END

COMMAND(EXTOPJC)
  ERROR(COMMAND_ERROR_NOTIMP); /* %^ */
END

COMMAND(EXTOPJD)
  ERROR(COMMAND_ERROR_NOTIMP); /* %< */
END

COMMAND(EXTOPJE)
  ERROR(COMMAND_ERROR_NOTIMP); /* %> */
END

COMMAND(EXTOPJF)
  ERROR(COMMAND_ERROR_NOTIMP); /* %? */
END

COMMAND(EXTOPJG)
  ERROR(COMMAND_ERROR_NOTIMP); /* %= */
END

COMMAND(EXTOPJH)
  ERROR(COMMAND_ERROR_NOTIMP); /* %* */
END

COMMAND(EXTOPJI)
  ERROR(COMMAND_ERROR_NOTIMP); /* %/ */
END

COMMAND(EXTOPJJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* %% */
END

COMMAND(EXTOPJK)
  ERROR(COMMAND_ERROR_NOTIMP); /* %! */
END

COMMAND(EXTOPJL)
  ERROR(COMMAND_ERROR_NOTIMP); /* %# */
END

COMMAND(EXTOPJM)
  ERROR(COMMAND_ERROR_NOTIMP); /* %& */
END

COMMAND(EXTOPJN)
  ERROR(COMMAND_ERROR_NOTIMP); /* %\ */
END

COMMAND(EXTOPJO)
  ERROR(COMMAND_ERROR_NOTIMP); /* %` */
END

COMMAND(EXTOPJP)
  ERROR(COMMAND_ERROR_NOTIMP); /* %' */
END

COMMAND(EXTOPJQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* %@ */
END

COMMAND(EXTOPKC)
  ERROR(COMMAND_ERROR_NOTIMP); /* !^ */
END

COMMAND(EXTOPKD)
  ERROR(COMMAND_ERROR_NOTIMP); /* !< */
END

COMMAND(EXTOPKE)
  ERROR(COMMAND_ERROR_NOTIMP); /* !> */
END

COMMAND(EXTOPKF)
  ERROR(COMMAND_ERROR_NOTIMP); /* !? */
END

COMMAND(EXTOPKG)
  ERROR(COMMAND_ERROR_NOTIMP); /* != */
END

COMMAND(EXTOPKH)
  ERROR(COMMAND_ERROR_NOTIMP); /* !* */
END

COMMAND(EXTOPKI)
  ERROR(COMMAND_ERROR_NOTIMP); /* !/ */
END

COMMAND(EXTOPKJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* !% */
END

COMMAND(EXTOPKK)
  ERROR(COMMAND_ERROR_NOTIMP); /* !! */
END

COMMAND(EXTOPKL)
  ERROR(COMMAND_ERROR_NOTIMP); /* !# */
END

COMMAND(EXTOPKM)
  ERROR(COMMAND_ERROR_NOTIMP); /* !& */
END

COMMAND(EXTOPKN)
  ERROR(COMMAND_ERROR_NOTIMP); /* !\ */
END

COMMAND(EXTOPKO)
  ERROR(COMMAND_ERROR_NOTIMP); /* !` */
END

COMMAND(EXTOPKP)
  ERROR(COMMAND_ERROR_NOTIMP); /* !' */
END

COMMAND(EXTOPKQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* !@ */
END

COMMAND(EXTOPLC)
  ERROR(COMMAND_ERROR_NOTIMP); /* #^ */
END

COMMAND(EXTOPLD)
  ERROR(COMMAND_ERROR_NOTIMP); /* #< */
END

COMMAND(EXTOPLE)
  ERROR(COMMAND_ERROR_NOTIMP); /* #> */
END

COMMAND(EXTOPLF)
  ERROR(COMMAND_ERROR_NOTIMP); /* #? */
END

COMMAND(EXTOPLG)
  ERROR(COMMAND_ERROR_NOTIMP); /* #= */
END

COMMAND(EXTOPLH)
  ERROR(COMMAND_ERROR_NOTIMP); /* #* */
END

COMMAND(EXTOPLI)
  ERROR(COMMAND_ERROR_NOTIMP); /* #/ */
END

COMMAND(EXTOPLJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* #% */
END

COMMAND(EXTOPLK)
  ERROR(COMMAND_ERROR_NOTIMP); /* #! */
END

COMMAND(EXTOPLL)
  ERROR(COMMAND_ERROR_NOTIMP); /* ## */
END

COMMAND(EXTOPLM)
  ERROR(COMMAND_ERROR_NOTIMP); /* #& */
END

COMMAND(EXTOPLN)
  ERROR(COMMAND_ERROR_NOTIMP); /* #\ */
END

COMMAND(EXTOPLO)
  ERROR(COMMAND_ERROR_NOTIMP); /* #` */
END

COMMAND(EXTOPLP)
  ERROR(COMMAND_ERROR_NOTIMP); /* #' */
END

COMMAND(EXTOPLQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* #@ */
END

COMMAND(EXTOPMC)
  ERROR(COMMAND_ERROR_NOTIMP); /* &^ */
END

COMMAND(EXTOPMD)
  ERROR(COMMAND_ERROR_NOTIMP); /* &< */
END

COMMAND(EXTOPME)
  ERROR(COMMAND_ERROR_NOTIMP); /* &> */
END

COMMAND(EXTOPMF)
  ERROR(COMMAND_ERROR_NOTIMP); /* &? */
END

COMMAND(EXTOPMG)
  ERROR(COMMAND_ERROR_NOTIMP); /* &= */
END

COMMAND(EXTOPMH)
  ERROR(COMMAND_ERROR_NOTIMP); /* &* */
END

COMMAND(EXTOPMI)
  ERROR(COMMAND_ERROR_NOTIMP); /* &/ */
END

COMMAND(EXTOPMJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* &% */
END

COMMAND(EXTOPMK)
  ERROR(COMMAND_ERROR_NOTIMP); /* &! */
END

COMMAND(EXTOPML)
  ERROR(COMMAND_ERROR_NOTIMP); /* &# */
END

COMMAND(EXTOPMM)
  ERROR(COMMAND_ERROR_NOTIMP); /* && */
END

COMMAND(EXTOPMN)
  ERROR(COMMAND_ERROR_NOTIMP); /* &\ */
END

COMMAND(EXTOPMO)
  ERROR(COMMAND_ERROR_NOTIMP); /* &` */
END

COMMAND(EXTOPMP)
  ERROR(COMMAND_ERROR_NOTIMP); /* &' */
END

COMMAND(EXTOPMQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* &@ */
END

COMMAND(EXTOPNC)
  ERROR(COMMAND_ERROR_NOTIMP); /* \^ */
END

COMMAND(EXTOPND)
  ERROR(COMMAND_ERROR_NOTIMP); /* \< */
END

COMMAND(EXTOPNE)
  ERROR(COMMAND_ERROR_NOTIMP); /* \> */
END

COMMAND(EXTOPNF)
  ERROR(COMMAND_ERROR_NOTIMP); /* \? */
END

COMMAND(EXTOPNG)
  ERROR(COMMAND_ERROR_NOTIMP); /* \= */
END

COMMAND(EXTOPNH)
  ERROR(COMMAND_ERROR_NOTIMP); /* \* */
END

COMMAND(EXTOPNI)
  ERROR(COMMAND_ERROR_NOTIMP); /* \/ */
END

COMMAND(EXTOPNJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* \% */
END

COMMAND(EXTOPNK)
  ERROR(COMMAND_ERROR_NOTIMP); /* \! */
END

COMMAND(EXTOPNL)
  ERROR(COMMAND_ERROR_NOTIMP); /* \# */
END

COMMAND(EXTOPNM)
  ERROR(COMMAND_ERROR_NOTIMP); /* \& */
END

COMMAND(EXTOPNN)
  ERROR(COMMAND_ERROR_NOTIMP); /* \\ */
END

COMMAND(EXTOPNO)
  ERROR(COMMAND_ERROR_NOTIMP); /* \` */
END

COMMAND(EXTOPNP)
  ERROR(COMMAND_ERROR_NOTIMP); /* \' */
END

COMMAND(EXTOPNQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* \@ */
END

COMMAND(EXTOPOC)
  ERROR(COMMAND_ERROR_NOTIMP); /* `^ */
END

COMMAND(EXTOPOD)
  ERROR(COMMAND_ERROR_NOTIMP); /* `< */
END

COMMAND(EXTOPOE)
  ERROR(COMMAND_ERROR_NOTIMP); /* `> */
END

COMMAND(EXTOPOF)
  ERROR(COMMAND_ERROR_NOTIMP); /* `? */
END

COMMAND(EXTOPOG)
  ERROR(COMMAND_ERROR_NOTIMP); /* `= */
END

COMMAND(EXTOPOH)
  ERROR(COMMAND_ERROR_NOTIMP); /* `* */
END

COMMAND(EXTOPOI)
  ERROR(COMMAND_ERROR_NOTIMP); /* `/ */
END

COMMAND(EXTOPOJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* `% */
END

COMMAND(EXTOPOK)
  ERROR(COMMAND_ERROR_NOTIMP); /* `! */
END

COMMAND(EXTOPOL)
  ERROR(COMMAND_ERROR_NOTIMP); /* `# */
END

COMMAND(EXTOPOM)
  ERROR(COMMAND_ERROR_NOTIMP); /* `& */
END

COMMAND(EXTOPON)
  ERROR(COMMAND_ERROR_NOTIMP); /* `\ */
END

COMMAND(EXTOPOO)
  ERROR(COMMAND_ERROR_NOTIMP); /* `` */
END

COMMAND(EXTOPOP)
  ERROR(COMMAND_ERROR_NOTIMP); /* `' */
END

COMMAND(EXTOPOQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* `@ */
END

COMMAND(EXTOPPC)
  ERROR(COMMAND_ERROR_NOTIMP); /* '^ */
END

COMMAND(EXTOPPD)
  ERROR(COMMAND_ERROR_NOTIMP); /* '< */
END

COMMAND(EXTOPPE)
  ERROR(COMMAND_ERROR_NOTIMP); /* '> */
END

COMMAND(EXTOPPF)
  ERROR(COMMAND_ERROR_NOTIMP); /* '? */
END

COMMAND(EXTOPPG)
  ERROR(COMMAND_ERROR_NOTIMP); /* '= */
END

COMMAND(EXTOPPH)
  ERROR(COMMAND_ERROR_NOTIMP); /* '* */
END

COMMAND(EXTOPPI)
  ERROR(COMMAND_ERROR_NOTIMP); /* '/ */
END

COMMAND(EXTOPPJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* '% */
END

COMMAND(EXTOPPK)
  ERROR(COMMAND_ERROR_NOTIMP); /* '! */
END

COMMAND(EXTOPPL)
  ERROR(COMMAND_ERROR_NOTIMP); /* '# */
END

COMMAND(EXTOPPM)
  ERROR(COMMAND_ERROR_NOTIMP); /* '& */
END

COMMAND(EXTOPPN)
  ERROR(COMMAND_ERROR_NOTIMP); /* '\ */
END

COMMAND(EXTOPPO)
  ERROR(COMMAND_ERROR_NOTIMP); /* '` */
END

COMMAND(EXTOPPP)
  ERROR(COMMAND_ERROR_NOTIMP); /* '' */
END

COMMAND(EXTOPPQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* '@ */
END

COMMAND(EXTOPQC)
  ERROR(COMMAND_ERROR_NOTIMP); /* @^ */
END

COMMAND(EXTOPQD)
  ERROR(COMMAND_ERROR_NOTIMP); /* @< */
END

COMMAND(EXTOPQE)
  ERROR(COMMAND_ERROR_NOTIMP); /* @> */
END

COMMAND(EXTOPQF)
  ERROR(COMMAND_ERROR_NOTIMP); /* @? */
END

COMMAND(EXTOPQG)
  ERROR(COMMAND_ERROR_NOTIMP); /* @= */
END

COMMAND(EXTOPQH)
  ERROR(COMMAND_ERROR_NOTIMP); /* @* */
END

COMMAND(EXTOPQI)
  ERROR(COMMAND_ERROR_NOTIMP); /* @/ */
END

COMMAND(EXTOPQJ)
  ERROR(COMMAND_ERROR_NOTIMP); /* @% */
END

COMMAND(EXTOPQK)
  ERROR(COMMAND_ERROR_NOTIMP); /* @! */
END

COMMAND(EXTOPQL)
  ERROR(COMMAND_ERROR_NOTIMP); /* @# */
END

COMMAND(EXTOPQM)
  ERROR(COMMAND_ERROR_NOTIMP); /* @& */
END

COMMAND(EXTOPQN)
  ERROR(COMMAND_ERROR_NOTIMP); /* @\ */
END

COMMAND(EXTOPQO)
  ERROR(COMMAND_ERROR_NOTIMP); /* @` */
END

COMMAND(EXTOPQP)
  ERROR(COMMAND_ERROR_NOTIMP); /* @' */
END

COMMAND(EXTOPQQ)
  ERROR(COMMAND_ERROR_NOTIMP); /* @@ */
END

