' """
FILE: xml.bas

This is the BASIC import file for the module xml.

This file was generated by headerer.pl from the file interface.c
Do not edit this file, rather edit the file interface.c and use
headerer.pl to regenerate this file.
"""

module xml

REM """
The module xml.bas is based on the Gnome libxml2 library.
"""
' FUNCTION DECLARATIONS 
declare sub     ::ParseFile    alias "sbxmlParseFile"     lib "xml"
declare sub     ::NewDoc       alias "sbxmlNewDoc"        lib "xml"
declare sub     ::FreeDoc      alias "sbxmlFreeDoc"       lib "xml"
declare sub     ::GetChildren  alias "getchildren"        lib "xml"
declare sub     ::SetChildren  alias "setchildren"        lib "xml"
declare sub     ::GetNext      alias "getnext"            lib "xml"
declare sub     ::SetNext      alias "setnext"            lib "xml"
declare sub     ::GetPrev      alias "getprev"            lib "xml"
declare sub     ::SetPrev      alias "setprev"            lib "xml"
declare sub     ::GetParent    alias "getparent"          lib "xml"
declare sub     ::SetParent    alias "setparent"          lib "xml"
declare sub     ::SetProp      alias "sbxmlSetProp"       lib "xml"
declare sub     ::GetProp      alias "sbxmlGetProp"       lib "xml"
declare sub     ::NewNs        alias "sbxmlNewNs"         lib "xml"
declare sub     ::FreeNs       alias "sbxmlFreeNs"        lib "xml"
declare sub     ::NewChild     alias "sbxmlNewChild"      lib "xml"
declare sub     ::NewTextChild alias "sbxmlNewTextChild"  lib "xml"
declare sub     ::NewDocNode   alias "sbxmlNewDocNode"    lib "xml"
declare sub     ::Doc2XML      alias "sbxmlDocDumpMemory" lib "xml"

end module
