' """
FILE: nt.bas

This is the BASIC import file for the module nt.

This file was generated by headerer.pl from the file 
Do not edit this file, rather edit the file  and use
headerer.pl to regenerate this file.
"""

module nt

' FUNCTION DECLARATIONS 
declare sub     ::RegRead         alias "regread"            lib "nt"
declare sub     ::RegDel          alias "regdel"             lib "nt"
declare sub     ::RegWrite        alias "regwrite"           lib "nt"
declare sub     ::MsgBox          alias "msgbox"             lib "nt"
declare sub     ::ShutDown        alias "shutdown_nt"        lib "nt"
declare sub     ::ListProcesses   alias "proclist"           lib "nt"
declare sub     ::StartService    alias "nt_startservice"    lib "nt"
declare sub     ::StopService     alias "nt_stopservice"     lib "nt"
declare sub     ::PauseService    alias "nt_pauseservice"    lib "nt"
declare sub     ::ContinueService alias "nt_continueservice" lib "nt"
declare sub     ::HardLink        alias "nt_hardlink"        lib "nt"

end module
