perl jamal.pl -m macros.jim audio.html.jam ../../html/audio.html
perl jamal.pl -m macros.jim author.html.jam ../../html/author.html
perl jamal.pl -m macros.jim body.html.jam ../../html/body.html
perl jamal.pl -m macros.jim documentation.html.jam ../../html/documentation.html
perl jamal.pl -m macros.jim download.html.jam ../../html/download.html
perl jamal.pl -m macros.jim feature.html.jam ../../html/feature.html
perl jamal.pl -m macros.jim future.html.jam ../../html/future.html
perl jamal.pl -m macros.jim general.html.jam ../../html/general.html
perl jamal.pl -m macros.jim head.html.jam ../../html/head.html
perl jamal.pl -m macros.jim index.html.jam ../../html/index.html
perl jamal.pl -m macros.jim install.html.jam ../../html/install.html
perl jamal.pl -m macros.jim license.html.jam ../../html/license.html
perl jamal.pl -m macros.jim main.html.jam ../../html/main.html
perl jamal.pl -m macros.jim menu.html.jam ../../html/menu.html
perl jamal.pl -m macros.jim news.html.jam ../../html/news.html
perl jamal.pl -m macros.jim news17.html.jam ../../html/news17.html
perl jamal.pl -m macros.jim news18.html.jam ../../html/news18.html
perl jamal.pl -m macros.jim news19.html.jam ../../html/news19.html
perl jamal.pl -m macros.jim news20.html.jam ../../html/news20.html
perl jamal.pl -m macros.jim support.html.jam ../../html/support.html
