' """
FILE: dyc.bas

This is the BASIC import file for the module dyc.

This file was generated by headerer.pl from the file interface.c
Do not edit this file, rather edit the file interface.c and use
headerer.pl to regenerate this file.
"""

module dyc

' FUNCTION DECLARATIONS 
declare sub     ::dyc alias "dyc" lib "dyc"

end module
